- src/components/Step/step.scss
- Add max width for input
closes #1
> Add max width for input

- src/components/Alert/alert.scss
- src/components/Alert/index.jsx
- src/components/Hint/hint.scss
- src/components/Hint/index.jsx
- src/components/LanguageSwitch/index.jsx
- src/components/LanguageSwitch/language-switch.scss
- src/components/Progress/progress.scss
- src/localization/en-us.json
- src/pages/LandingPage/components/Header/header.scss
- src/pages/LandingPage/components/Header/index.jsx
- src/pages/LandingPage/landing-page.scss
- src/pages/LearnPage/components/Header/header.scss
- src/pages/LearnPage/components/InteractiveArea/interactive-area.scss
- src/pages/LearnPage/components/Step/step.scss
> Fix responsive problems

- src/localization/en-us.json
- src/localization/tr-tr.json
- src/pages/LearnPage/components/InteractiveArea/index.jsx
- src/pages/LearnPage/components/ReportStep/index.jsx
- src/pages/LearnPage/components/ReportStep/report-step.scss
> Add issue template and report link to `LearnPage`

- src/pages/_app.js
- src/pages/_document.js
- `_document.js` created.
- `<Head>` moved into `_document.js`
> UPDATE: _document.js added. Head moved into document

- src/cheatsheet.json
- src/data.json
- src/localization/en-us.json
- src/localization/tr-tr.json
> Fix Asterisk Typo 

- src/components/LanguageSwitch/LanguageSwitch.module.css
- src/components/LanguageSwitch/index.jsx
> #112: Language selection area edited

- src/components/Button/Button.module.css
> #105: The bug of GitHub button has been fixed.

- src/localization/zh-cn/learn.json
> 修正一处专业名词上的错误

- src/localization/zh-cn/cheatsheet.json
- src/localization/zh-cn/learn.json
Fix a few errors based on feedback
> Fixing `Chinese` errors in details 2021.12.18

- package.json
- src/components/Step/index.jsx
- yarn.lock
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Added confetti to the last step of a lesson
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No
* **What is the new behavior (if this is a feature change)?**
Added `canvas-confetti` packages. You have to run the `yarn install` or `yarn` command to see the changes on the branch.
closes #145
> Add confetti to the last step of a lesson

- src/localization/es/learn.json
Fixed a small Spanish grammar issue in `learn.json`.
Congratulations on this excellent project ❤️
> [Lang] fixing Spanish translations in `learn.json`

- src/localization/en/learn.json
> update step 18-20 to make it more clear where the modifiers go

- src/localization/en/learn.json
change "sensitiveness" to "sensitivity"
> Fix typo (regex-101)(en)

- src/localization/en/learn.json
cleaned up language in flags intro lesson
> Fix grammar (regex-101)(en)

- src/localization/en/learn.json
reworded curly braces exercise
> Fix grammar (lesson/regex101)

- src/components/InteractiveArea/index.tsx
> Reset match and success state when has error (learn)

- src/localization/en/learn.json
Closes #150 
I'm not sure how to build the site locally, so forgive me if this breaks linting or CI
> Add note about matching a single digit to Step 27 (lesson/regex101) 

- src/localization/en/learn.json
> Fix grammar (lesson/regex101/positiveLookbehind)

- src/localization/en/learn.json
> Fix parenthesis typo (en/regex-101)

- src/localization/es/learn.json
> Fix parentesis typo (es/regex-101)

- src/localization/fr/lessons/regexForSeo.json
This pull request adds the french language for the ``regexForSeo.json`` file.
Closes #248
> feat(translations): add french for regexForSeo.json

- src/localization/fr/learn.json
I made some corrections in the french translation
In reference of the #245
> Improving french translation

- src/localization/es/lessons/regexForSeo.json
I finished the translation for all the tutorial steps from English to Spanish.
If you have any kind of question about the translation or any observation please feel free to ask.
> [Learn]: Translation support for Regex For SEO tutorial (Spanish)

- src/localization/zh-cn/lessons/regexForSeo.json
regexForSeo.json translated to Chinese，#257
> Regex For SEO translate to Chinese

- src/localization/ru/lessons/regexForSeo.json
This pull request adds the Russian language for the `regexForSeo.json` file.
Closes #247
> [Learn]: Translation support for Regex For SEO tutorial (Russian)

- README.md
I am currently working on the translation 🇬🇪.
It'll be available very soon...
> Added current status for Georgian translation

- .gitignore
- src/localization/en/general.json
This will fix the grammar in en/general.json.
> Fix grammar in en/general.json

- src/components/PlaygroundEditor.tsx
> style:button chinese text wrap

- src/components/CheatsheetDemo.tsx
- src/components/FlagSelect.tsx
- src/components/Header.tsx
- src/components/InteractiveArea.tsx
- src/components/LanguageSelect.tsx
- src/components/LearnFooter.tsx
- src/components/LessonBox.tsx
- src/components/PlaygroundEditor.tsx
- src/components/Progress.tsx
- src/components/ReportPlayground.tsx
- src/components/Step.tsx
- src/localization/index.ts
- src/pages/[lang]/learn/index.tsx
- src/pages/_app.tsx
- src/pages/_document.tsx
- src/utils/useLanguageDirection.tsx
- I added a hook to determine text direction (LTR or RTL) based on the page's language (`useLanguageDirection`). 
- Due to the unavailability of `useRouter` within document.tsx, I addressed this by assigning the `dir` attribute to the main div in app.tsx. 
- **Todo**: Currently, 'tr' is shown as an RTL language; additional RTL languages should be added."
> feature: rtl language support

- src/localization/ko/general.json
- src/localization/ko/landing.json
- src/localization/ko/learn.json
Improved text and added missing words in Korean localization files.
> Update Korean localization
